name: "Autogenerate"
description: "Generate and publish Dockerfiles and Stackbrew Library files"
inputs:
  json:
    description: "JSON stringified object containing all the inputs from the calling workflow"
    required: true
  secrets:
    description: "JSON stringified object containing all the secrets from the calling workflow"
    required: true
  variables:
    description: "JSON stringified object containing all the variables from the calling workflow"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Node.js 18.x
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
      with:
        node-version: 18.x

    - name: Install dependencies
      shell: bash
      run: |
        npm ci

    - name: Generate Dockerfiles
      shell: bash
      run: |
        git rm -q -rf balena-base-images
        npm run all
        npm run all-dockerhub

    # https://github.com/crazy-max/ghaction-import-gpg
    - name: Import GPG private key
      id: import-gpg
      uses: crazy-max/ghaction-import-gpg@111c56156bcc6918c056dbef52164cfa583dc549 # v5.2.0
      with:
        gpg_private_key: ${{ fromJSON(inputs.secrets).GPG_PRIVATE_KEY }}
        passphrase: ${{ fromJSON(inputs.secrets).GPG_PASSPHRASE }}
        git_config_global: true
        git_user_signingkey: true
        git_commit_gpgsign: true

    - name: Commit and create patch
      shell: bash
      env:
        GIT_AUTHOR_NAME: ${{ steps.import-gpg.outputs.name }}
        GIT_AUTHOR_EMAIL: ${{ steps.import-gpg.outputs.email }}
        GIT_COMMITTER_NAME: ${{ steps.import-gpg.outputs.name }}
        GIT_COMMITTER_EMAIL: ${{ steps.import-gpg.outputs.email }}
      run: |
        git add -A balena-base-images
        git commit -m "Autogenerated Dockerfiles" -m "[skip ci]"
        git format-patch -k -s HEAD^ -o ${{ runner.temp }}/patches

    # https://github.com/actions/upload-artifact
    - name: Upload patches artifact
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
      with:
        name: patches-${{ github.event.pull_request.head.sha }}
        path: ${{ runner.temp }}/patches
        retention-days: 90

    - name: Generate Stackbrew Library files
      shell: bash
      run: |
        npm run all-lib
        tar czf ${{ runner.temp }}/libs.tgz -C library .

    # https://github.com/actions/upload-artifact
    - name: Upload libs artifact
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
      with:
        name: libs-${{ github.event.pull_request.head.sha }}
        path: ${{ runner.temp }}/libs.tgz
        retention-days: 90
