name: "Autogenerate"
description: "Generate Dockerfiles and Libraries"
inputs:
  json:
    description: "JSON stringified object containing all the inputs from the calling workflow"
    required: true
  secrets:
    description: "JSON stringified object containing all the secrets from the calling workflow"
    required: true
  variables:
    description: "JSON stringified object containing all the variables from the calling workflow"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Node.js 18.x
      uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3
      with:
        node-version: 18.x

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Generate Dockerfiles
      shell: bash
      id: dockerfiles
      run: |
        git rm -q -rf balena-base-images
        npm run all
        git add -A balena-base-images

        if [ -n "$(git status --porcelain balena-base-images)" ]
        then
          echo "changed=true" >> $GITHUB_OUTPUT
        fi

    - name: Generate Libraries
      if: steps.dockerfiles.outputs.changed == 'true'
      shell: bash
      run: |
        git rm -q -rf library || true
        npm run all-lib
        git add -A library

    - name: Commit and push changes
      if: steps.dockerfiles.outputs.changed == 'true'
      shell: bash
      env:
        GIT_AUTHOR_NAME: flowzone-app[bot]
        GIT_AUTHOR_EMAIL: 124931076+flowzone-app[bot]@users.noreply.github.com
        GIT_COMMITTER_NAME: flowzone-app[bot]
        GIT_COMMITTER_EMAIL: 124931076+flowzone-app[bot]@users.noreply.github.com
      run: |
        git commit -m "Autogenerated Dockerfiles" -m "[skip ci]"
        git push origin HEAD:refs/heads/${{ github.base_ref }}
