name: "Autogenerate"
description: "Generate Dockerfiles and Libraries"
inputs:
  json:
    description: "JSON stringified object containing all the inputs from the calling workflow"
    required: true
  secrets:
    description: "JSON stringified object containing all the secrets from the calling workflow"
    required: true
  variables:
    description: "JSON stringified object containing all the variables from the calling workflow"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Node.js 18.x
      uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3
      with:
        node-version: 18.x

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Generate Dockerfiles
      shell: bash
      id: dockerfiles
      run: |
        git rm -q -rf balena-base-images
        npm run all
        git add -A balena-base-images

        if [ -n "$(git status --porcelain balena-base-images)" ]
        then
          echo "changed=true" >> $GITHUB_OUTPUT
        fi

    - name: Generate Libraries
      if: steps.dockerfiles.outputs.changed == 'true'
      shell: bash
      run: |
        git rm -q -rf library || true
        npm run all-lib
        git add -A library

    - name: Commit changes
      if: steps.dockerfiles.outputs.changed == 'true'
      shell: bash
      env:
        GIT_AUTHOR_NAME: flowzone-app[bot]
        GIT_AUTHOR_EMAIL: 124931076+flowzone-app[bot]@users.noreply.github.com
        GIT_COMMITTER_NAME: flowzone-app[bot]
        GIT_COMMITTER_EMAIL: 124931076+flowzone-app[bot]@users.noreply.github.com
      run: |
        git commit -m "Autogenerated Dockerfiles" -m "[skip ci]"

    # https://github.com/marketplace/actions/github-app-token
    - name: Generate GitHub App installation token
      uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1.8.0
      if: steps.dockerfiles.outputs.changed == 'true'
      id: gh_app_token
      with:
        app_id: ${{ fromJSON(inputs.json).app_id }}
        installation_id: ${{ fromJSON(inputs.json).installation_id }}
        private_key: ${{ fromJSON(inputs.secrets).GH_APP_PRIVATE_KEY }}
        permissions: ${{ fromJSON(inputs.json).token_scope }}

    # https://github.com/marketplace/actions/github-push
    - name: Push changes
      uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6 # v0.6.0
      if: steps.dockerfiles.outputs.changed == 'true'
      with:
        github_token: ${{ steps.gh_app_token.outputs.token }}
        branch: ${{ github.ref }}
