name: bake

"on":
  pull_request:
    branches:
      - main
      - master
  workflow_run:
    workflows: []
    types:
      - completed
  workflow_dispatch:
    inputs:
      no-push:
        description: Do not push to DockerHub
        required: false
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  LIBRARY: ""

jobs:
  prepare:
    name: Prepare matrix
    runs-on: ubuntu-latest

    outputs:
      bake-targets: ${{ steps.bake-targets.outputs.matrix }}

    steps:

      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set matrix
        id: bake-targets
        run: |
          set -x
          targets="$(jq -cr '.group.default.targets' $LIBRARY)"
          echo "matrix=$targets" >> $GITHUB_OUTPUT

  bake:
    name: Bake images
    runs-on: ubuntu-latest
    # timeout-minutes: 480
    needs:
      - prepare

    strategy:
      # max-parallel: 20
      fail-fast: false
      matrix:
        target: ${{ fromJSON(needs.prepare.outputs.bake-targets) }}

    steps:

      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # https://github.com/docker/setup-qemu-action
      - name: Setup QEMU
        uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2
        with:
          platforms: all
          # https://hub.docker.com/r/tonistiigi/binfmt
          image: tonistiigi/binfmt:qemu-v6.2.0

      # https://github.com/docker/setup-buildx-action
      - name: Setup buildx
        uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2
        with:
          driver-opts: network=host
          install: true

      # https://github.com/docker/login-action
      - name: Login to DockerHub
        uses: docker/login-action@v2
        if: ${{ inputs.no-push != true && github.event_name != 'pull_request' }}
        with:
          registry: docker.io
          username: ${{ secrets.BALENAIMAGES_USER }}
          password: ${{ secrets.BALENAIMAGES_TOKEN }}

      # https://github.com/docker/bake-action
      - name: Docker bake
        id: docker_bake
        uses: docker/bake-action@f32f8b8d70bc284af19f8148dd14ad1d2fbc6c28 # v3
        with:
          workdir: balena-base-images
          files: ${{ github.workspace }}/${{ env.LIBRARY }}
          targets: ${{ matrix.target }}
          push: ${{ inputs.no-push != true && github.event_name != 'pull_request' }}
          provenance: false
